- name: download artifact
  get_url:
     url: https://github.com/Anji399/air/raw/master/target/airtel.war
     dest: /tmp
- name: copy artifact
  copy:
     src: /tmp/airtel.war
     dest: /opt/tomcat/webapps/airtel.war
     owner: tomcat
     group: tomcat
     remote_src: yes
 
